name: coie-prod

services:
  api-migrate:
    build:
      context: ./api
      target: prod-migrate
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:?required}:${POSTGRES_PASSWORD:?required}@db:5432/${POSTGRES_DB:?required}"
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  api:
    command: ["node", "src/index.js"]
    volumes:
      - ./data-prod:/data:ro
      - ./data-prod/logs/api:/app/logs
    build:
      target: prod-runtime
    restart: unless-stopped
    init: true
    read_only: true
    tmpfs:
      - /tmp
    env_file:
      - ./api/.env.prod
    depends_on:
      db:
        condition: service_healthy
      api-migrate:
        condition: service_completed_successfully

  worker:
    command: ["node", "src/worker.js"]
    volumes:
      - ./data-prod:/data:ro
      - ./data-prod/logs/api:/app/logs
    build:
      target: prod-runtime
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    env_file:
      - ./api/.env.prod
    depends_on:
      db:
        condition: service_healthy
      api-migrate:
        condition: service_completed_successfully

  bot:
    volumes:
      - ./data-prod:/data
    build:
      target: prod-runtime
    # restart: unless-stopped
    env_file:
      - ./bot/.env.prod

  # web:
  #   build:
  #     target: prod-runtime
  #   restart: unless-stopped
  #   environment:
  #     NODE_ENV: production
  #   env_file:
  #     - ./web.env
  #   depends_on:
  #     - api
  #   ports:
  #     - "80:3001"
