services:
  api-migrate:
    build:
      context: ./api
      target: prod-migrate
    container_name: offerings_api_migrate
    command: ["npm", "exec", "prisma", "migrate", "deploy"]
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://${POSTGRES_USER:?required}:${POSTGRES_PASSWORD:?required}@db:5432/${POSTGRES_DB:?required}"
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  api:
    build:
      target: prod-runtime
    restart: unless-stopped
    init: true
    read_only: true
    tmpfs:
      - /tmp
    environment:
      NODE_ENV: production
    env_file:
      - ./api/.env.prod
    depends_on:
      db:
        condition: service_healthy
      api-migrate:
        condition: service_completed_successfully

  bot:
    build:
      target: prod-runtime
    # restart: unless-stopped
    environment:
      NODE_ENV: production
    env_file:
      - ./bot/.env.prod

  # web:
  #   build:
  #     target: prod-runtime
  #   container_name: offerings_web
  #   restart: unless-stopped
  #   environment:
  #     NODE_ENV: production
  #   env_file:
  #     - ./web.env
  #   depends_on:
  #     - api
  #   ports:
  #     - "80:3001"
