-- Fresh database bootstrap only: replace the empty columns generated by Prisma.
-- PostgreSQL then keeps location in sync with latitude and longitude.
ALTER TABLE "Group" DROP COLUMN "location";
ALTER TABLE "Group"
  ADD COLUMN "location" geography(Point, 4326)
  GENERATED ALWAYS AS (
    CASE
      WHEN "latitude" IS NOT NULL AND "longitude" IS NOT NULL
      THEN ST_SetSRID(ST_MakePoint("longitude", "latitude"), 4326)::geography
      ELSE NULL
    END
  ) STORED;

ALTER TABLE "Venue" DROP COLUMN "location";
ALTER TABLE "Venue"
  ADD COLUMN "location" geography(Point, 4326)
  GENERATED ALWAYS AS (
    CASE
      WHEN "latitude" IS NOT NULL AND "longitude" IS NOT NULL
      THEN ST_SetSRID(ST_MakePoint("longitude", "latitude"), 4326)::geography
      ELSE NULL
    END
  ) STORED;

ALTER TABLE "Offering" DROP COLUMN "location";
ALTER TABLE "Offering"
  ADD COLUMN "location" geography(Point, 4326)
  GENERATED ALWAYS AS (
    CASE
      WHEN "latitude" IS NOT NULL AND "longitude" IS NOT NULL
      THEN ST_SetSRID(ST_MakePoint("longitude", "latitude"), 4326)::geography
      ELSE NULL
    END
  ) STORED;

CREATE INDEX "Group_location_idx" ON "Group" USING GIST ("location");
CREATE INDEX "Venue_location_idx" ON "Venue" USING GIST ("location");
CREATE INDEX "Offering_location_idx" ON "Offering" USING GIST ("location");

CREATE INDEX "VenueAlias_trgm_idx"
  ON "VenueAlias" USING GIN ("normalizedAlias" gin_trgm_ops);
